# To Be Done {#tbd}

Notwendig:

- Pandoc assumes some LaTeX packages to be availabe. See http://pandoc.org/MANUAL.html#creating-a-pdf.
- "References" statt "Literatur" unter HTML-Seite
- LaTeX Übersetzung
- Dezimaltrennzeichen vor allem von inline r-Code: Komma statt Punkt
- LaTeX Float
- LaTeX nocite
- LaTeX Code schreibt über Seitenränder -> manuell Zeilen ab Spalte 90 umbrechen
    - [x] auch wenn code chunk option `tidy`?
- Word zentriertes Bild ist linksbündig
- `'r format(Sys.time(), '%d. %B %Y')'` verursacht LaTeX Probleme
- custom block icons und favicon werden online nicht angezeigt
- Zitieren von Yihui. Bib-file entschlacken.

Zukünftig:

- LaTeX Text ist zentriert nach kaputter Tabelle
- auto create .zip RProject (vllt via makeZip.bat oder zip())
- autocompletion für `\@ref`
    - Atom-Editor kann das vielleicht https://discuss.atom.io/t/autocompletion-of-citeproc-references-in-markdown/28177 ?
- xtable bzw. generell LaTeX-Tabellen in Word und co möglich? Per Screenshot?
- citr geht nicht mehr
- mehrere Literaturverzeichnisse
- Packrat offline restore
    - `packrat::set_opts(local.repos = "packrat/src/")` ?
	- scheint noch offen zu sein https://github.com/rstudio/packrat/issues/287
- [x] Packrat lib outside of project folder
    - enabled in developer version: https://github.com/rstudio/packrat/issues/338#issuecomment-320553343
    - packrat/packrat.opts see ?"packrat-options"
    - packrat/lib/ verschiebbar? use.cache? -> not enabled on windows!
    - https://stackoverflow.com/questions/44676570/how-does-the-use-cache-feature-of-packrat-work
        - "Somewhere in between these options might make the most sense - users currate their list of large but commonly used packages to be symlinked (i.e.packrat::set_opts(external.packages=c('tidyverse', 'data.table')) ) and then put up with installing smaller packages on a project by project basis." or all packges: installed.packages()[,"Package"]
- hunspell und Umlaute
- R-Code in Custom Block und umgekehrt
- was kann bookdownplus besser? https://github.com/pzhaonet/bookdownplus
- interactive tutorial with https://rstudio.github.io/learnr/
- github-Links zu statistify.de-Links wandeln/umleiten

Im Moment noch nicht möglich:

- continuous spell checking in RStudio
- autocomplete `@ref` https://github.com/rstudio/rmarkdown/issues/958
- htmlwidget / DT-table als "Tabelle" statt als "Abbildung"


<!-- Ein paar falsch geschriebene Wörter für das Spellchecking-Beispiel -->
```{r wrongWords, eval=FALSE, include=FALSE}
"Worng eglish word."
"Falsches deutshes Wort."
```

