`r if (knitr:::is_html_output()) '# Literatur {-}'`
  <!-- 
  Das Literaturverzeichnis wird automatisch auf der letzten Seite (PDF) bzw. 
  unten auf jeder Website, die Referenzen enthält, erstellt.
  
  Nicht zitierte Quellen, die dennoch im Literaturverzeichnis erscheinen sollen,
  müssen in der index.Rmd im YAML header block 'nocite:' eingetragen werden.
  -->

```{r include=FALSE}
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'htmlwidgets', 'webshot', 'DT',
  'miniUI', 'tufte', 'servr', 'citr', 'rticles'
), 'packages.bib')
```

```{r sessionInfo}
sessionInfo()
```


<!-- add .zip to book's download area, so that the RProject (and not only the compiled book) can be downloaded -->

```{r makeZip, echo=FALSE, include=FALSE}
#zipfilename <- paste0("RProject_thesiswritingUsingRStudioAndBookdown_",
#                      Sys.Date())
#zipfiles <- list.files(getwd())
#zipextras <- list("-x .git")
#dest_path <- paste0(getwd(), zip)
##zip(zipfile = zipfilename, 
##    files = zipfiles,
##    extra = zipextras)
#tar(tarfile = zipfilename, 
#    files = zipfiles) #how to exclude packrat/lib ?
#    
#system("for /d %%a in (*) do (ECHO zip -r -p \"%%~na.zip\" \".\%%a\*\")")
#shell.exec("makeZip.bat")
```

